### PR TITLE
CORE 3, IHost, Linux/Docker

### PR DESCRIPTION
**Pull request by doug62**
Works with IHost and/or IWebHost, CORE 3 sample, Linux support.

### CODE REVIEW

**Comment by ffMathy** [comment]
@kg73 any chance you could hit that merge button? It's a wonderful library - unfortunately doesn't work on Linux.

**Comment by ffMathy** [comment]
Alternatively @kg73 if you want - you can set me as a maintainer for this repo. I'll take good care of it.

**Comment by ffMathy** [comment]
I published this fork and made some improvements too, here: https://github.com/ffMathy/FluffySpoon.AspNet.NGrok

**Comment by kg73** [comment]
Thanks for the reminder @ffMathy 
Feel free to submit a PR for your improvements as well, and I'd be happy to merge it in and push out an update NuGet package.

**Comment by ffMathy** [comment]
@kg73 thanks for access to the repo!

I decided to remove quite a lot of the old functionality and rewrite some relatively large parts. It's really nice of you to offer to merge in the PR improvements, but I think you might disagree with the changes made.

Feel free to take a look at them though.

I primarily changed how the project is now set up - see the README.md file here: https://github.com/ffMathy/FluffySpoon.AspNet.NGrok

Those are obviously breaking changes. If that still suits you, sure - we can merge it :+1: 🙇

**Comment by kbot7** [comment]
@ffMathy I've reviewed the changes in your fork, and I agree with the changes, specifically with using the `IHostedService` interface. I'd be happy to merge it over, if you'd please create a PR. 

I also have a branch with the HttpClient code broken out into a new project, and more properly encapsulated, with integration tests as well. I think I could merge it on top of your changes.

**Comment by ffMathy** [comment]
Alright! That's brilliant.

Currently investigating a null reference that I'm getting in my own project, but not the Sample project in the solution.

Once that's resolved, I can make a PR.

Main problem right now is that I also renamed a lot of namespaces etc. I'll have to rename those back.

**Pull request merged**
